In [4]:
import numpy as np

In [10]:
b = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = b.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [13]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [15]:
a_centered = np.subtract(a,mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [27]:
a_centered_sp = np.dot(a_centered[:,0],a_centered[:,1])
a_centered_sp

8.0

In [29]:
result = a_centered_sp / (a.shape[0]-1)
result

2.0

In [30]:
cov_matrix=np.cov(b)
cov_matrix

array([[1. , 2. ],
       [2. , 4.3]])

In [31]:
result_2 = cov_matrix[0,1]
result_2

2.0